/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-dim": "#cbdbf5",
        "on-tertiary-fixed-variant": "#444749",
        "on-primary-fixed-variant": "#3f465c",
        "on-secondary-fixed": "#261900",
        "inverse-primary": "#bec6e0",
        "on-tertiary-container": "#818486",
        "on-secondary-container": "#785a1a",
        "primary-fixed-dim": "#bec6e0",
        "tertiary": "#000000",
        "on-primary-container": "#7c839b",
        "primary-container": "#131b2e",
        "outline": "#76777d",
        "on-primary": "#ffffff",
        "primary-fixed": "#dae2fd",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#c4c7c9",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#eaf1ff",
        "surface-bright": "#f8f9ff",
        "secondary-fixed-dim": "#e9c176",
        "surface-variant": "#d3e4fe",
        "on-primary-fixed": "#131b2e",
        "background": "#f8f9ff",
        "on-surface": "#0b1c30",
        "error-container": "#ffdad6",
        "on-surface-variant": "#45464d",
        "error": "#ba1a1a",
        "secondary-container": "#fed488",
        "primary": "#000000",
        "outline-variant": "#c6c6cd",
        "tertiary-fixed": "#e0e3e5",
        "on-secondary": "#ffffff",
        "secondary": "#775a19",
        "surface-tint": "#565e74",
        "inverse-surface": "#213145",
        "secondary-fixed": "#ffdea5",
        "surface-container-high": "#dce9ff",
        "surface": "#f8f9ff",
        "on-error-container": "#93000a",
        "surface-container-highest": "#d3e4fe",
        "on-background": "#0b1c30",
        "tertiary-container": "#191c1e",
        "surface-container-low": "#eff4ff",
        "on-tertiary-fixed": "#191c1e",
        "surface-container": "#e5eeff",
        "on-secondary-fixed-variant": "#5d4201"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "lg": "48px",
        "gutter": "24px",
        "sm": "12px",
        "xl": "80px",
        "xs": "4px",
        "md": "24px",
        "base": "8px",
        "container-max": "1280px"
      },
      fontFamily: {
        "display-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
