variable "aws_region" {
  type        = string
  description = "The target AWS region for deployment"
  default     = "us-east-1"
}

variable "db_password" {
  type        = string
  description = "The database master password"
  sensitive   = true
}

variable "jwt_secret" {
  type        = string
  description = "The secret key used for signing JWT tokens"
  sensitive   = true
}

variable "ami_id" {
  type        = string
  description = "The custom AMI ID generated by HashiCorp Packer"
}
